/* Enums available here- https://developers.google.com/google-ads/api/rest/reference/rest/v20/AdGroup */

export enum GoogleAdsAccount {
  AMPLIFY_US = 'amplify_us',
  AMPLIFY_CA = 'amplify_ca',
}

export enum GoogleAdsResponseContentType {
  UNSPECIFIED = 'UNSPECIFIED',
  RESOURCE_NAME_ONLY = 'RESOURCE_NAME_ONLY',
  MUTABLE_RESOURCE = 'MUTABLE_RESOURCE',
}

export enum GoogleAdsCampaignStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  ENABLED = 'ENABLED',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
  UNKNOWN = 'UNKNOWN',
}

export enum GoogleAdsCampaignServingStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  SERVING = 'SERVING',
  NONE = 'NONE',
  ENDED = 'ENDED',
  PENDING = 'PENDING',
  SUSPENDED = 'SUSPENDED',
}

export enum GoogleAdsAdvertisingChannelType {
  SEARCH = 'SEARCH',
}

export enum GoogleAdsAdGroupStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  ENABLED = 'ENABLED',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
}

export enum GoogleAdsAdGroupType {
  SEARCH_STANDARD = 'SEARCH_STANDARD',
  SEARCH_DYNAMIC_ADS = 'SEARCH_DYNAMIC_ADS',
}

export enum GoogleAdsAdGroupAdStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  ENABLED = 'ENABLED',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
}

export enum GoogleAdsAdGroupAdAdStrength {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  PENDING = 'PENDING',
  NO_ADS = 'NO_ADS',
  POOR = 'POOR',
  AVERAGE = 'AVERAGE',
  GOOD = 'GOOD',
  EXCELLENT = 'EXCELLENT',
}

export enum GoogleAdsAdType {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  TEXT_AD = 'TEXT_AD',
  EXPANDED_TEXT_AD = 'EXPANDED_TEXT_AD',
  EXPANDED_DYNAMIC_SEARCH_AD = 'EXPANDED_DYNAMIC_SEARCH_AD',
  RESPONSIVE_SEARCH_AD = 'RESPONSIVE_SEARCH_AD',
}

export enum GoogleAdsAdGroupAdPrimaryStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  ELIGIBLE = 'ELIGIBLE',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
  PENDING = 'PENDING',
  LIMITED = 'LIMITED',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
}

export enum GoogleAdsAdGroupAdPrimaryStatusReason {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  CAMPAIGN_REMOVED = 'CAMPAIGN_REMOVED',
  CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED',
  CAMPAIGN_PENDING = 'CAMPAIGN_PENDING',
  CAMPAIGN_ENDED = 'CAMPAIGN_ENDED',
  AD_GROUP_PAUSED = 'AD_GROUP_PAUSED',
  AD_GROUP_REMOVED = 'AD_GROUP_REMOVED',
  AD_GROUP_AD_PAUSED = 'AD_GROUP_AD_PAUSED',
  AD_GROUP_AD_REMOVED = 'AD_GROUP_AD_REMOVED',
  AD_GROUP_AD_DISAPPROVED = 'AD_GROUP_AD_DISAPPROVED',
  AD_GROUP_AD_UNDER_REVIEW = 'AD_GROUP_AD_UNDER_REVIEW',
  AD_GROUP_AD_POOR_QUALITY = 'AD_GROUP_AD_POOR_QUALITY',
  AD_GROUP_AD_NO_ADS = 'AD_GROUP_AD_NO_ADS',
  AD_GROUP_AD_APPROVED_LABELED = 'AD_GROUP_AD_APPROVED_LABELED',
  AD_GROUP_AD_AREA_OF_INTEREST_ONLY = 'AD_GROUP_AD_AREA_OF_INTEREST_ONLY',
  AD_GROUP_AD_UNDER_APPEAL = 'AD_GROUP_AD_UNDER_APPEAL',
}

export enum GoogleAdsAssetType {
  TEXT = 'TEXT',
}

export enum GoogleAdsAssetSource {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  ADVERTISER = 'ADVERTISER',
  AUTOMATICALLY_CREATED = 'AUTOMATICALLY_CREATED',
}

export enum GoogleAdsServedAssetFieldType {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  HEADLINE_1 = 'HEADLINE_1',
  HEADLINE_2 = 'HEADLINE_2',
  HEADLINE_3 = 'HEADLINE_3',
  DESCRIPTION_1 = 'DESCRIPTION_1',
  DESCRIPTION_2 = 'DESCRIPTION_2',
  HEADLINE = 'HEADLINE',
  HEADLINE_IN_PORTRAIT = 'HEADLINE_IN_PORTRAIT',
  LONG_HEADLINE = 'LONG_HEADLINE',
  DESCRIPTION = 'DESCRIPTION',
  DESCRIPTION_IN_PORTRAIT = 'DESCRIPTION_IN_PORTRAIT',
  BUSINESS_NAME_IN_PORTRAIT = 'BUSINESS_NAME_IN_PORTRAIT',
  BUSINESS_NAME = 'BUSINESS_NAME',
  MARKETING_IMAGE = 'MARKETING_IMAGE',
  MARKETING_IMAGE_IN_PORTRAIT = 'MARKETING_IMAGE_IN_PORTRAIT',
  SQUARE_MARKETING_IMAGE = 'SQUARE_MARKETING_IMAGE',
  PORTRAIT_MARKETING_IMAGE = 'PORTRAIT_MARKETING_IMAGE',
  LOGO = 'LOGO',
  LANDSCAPE_LOGO = 'LANDSCAPE_LOGO',
  CALL_TO_ACTION = 'CALL_TO_ACTION',
  YOU_TUBE_VIDEO = 'YOU_TUBE_VIDEO',
  SITELINK = 'SITELINK',
  CALL = 'CALL',
  MOBILE_APP = 'MOBILE_APP',
  CALLOUT = 'CALLOUT',
  STRUCTURED_SNIPPET = 'STRUCTURED_SNIPPET',
  PRICE = 'PRICE',
  PROMOTION = 'PROMOTION',
  AD_IMAGE = 'AD_IMAGE',
  LEAD_FORM = 'LEAD_FORM',
  BUSINESS_LOGO = 'BUSINESS_LOGO',
}

export enum GoogleAdsAdGroupCriterionStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  ENABLED = 'ENABLED',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
}

export enum GoogleAdsKeywordMatchType {
  UNSPECIFIED = 'UNSPECIFIED',
  UNKNOWN = 'UNKNOWN',
  EXACT = 'EXACT',
  PHRASE = 'PHRASE',
  BROAD = 'BROAD',
}
