AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Manages the Facebook and Instagram campaign orchestration Lambda functions.

Globals:
  Function:
    Timeout: 300
    MemorySize: 256
    Architectures: [arm64]
    Runtime: nodejs20.x

Parameters:
  FacebookSqsQueueArn:
    Type: String
    Description: The ARN of the SQS queue for Facebook campaigns.
  InstagramSqsQueueArn:
    Type: String
    Description: The ARN of the SQS queue for Instagram campaigns.
  AmplifyManagerApiUrl:
    Type: String
    Description: The base URL for the Amplify Manager internal API.
  AmplifyIntegrationsApiUrl:
    Type: String
    Description: The base URL for the Amplify Integrations internal API.
  InternalApiKey:
    Type: String
    Description: The shared internal API key for authenticating with the services.
    NoEcho: true

Resources:
  FacebookCampaignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: facebook.main
      Environment:
        Variables:
          AMPLIFY_MANAGER_API_URL: !Ref AmplifyManagerApiUrl
          AMPLIFY_INTEGRATIONS_API_URL: !Ref AmplifyIntegrationsApiUrl
          INTERNAL_API_KEY: !Ref InternalApiKey
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !Ref FacebookSqsQueueArn
            BatchSize: 1
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: ['src/facebook.ts']
        Format: cjs
        Minify: true

  InstagramCampaignFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: instagram.main
      Environment:
        Variables:
          AMPLIFY_MANAGER_API_URL: !Ref AmplifyManagerApiUrl
          AMPLIFY_INTEGRATIONS_API_URL: !Ref AmplifyIntegrationsApiUrl
          INTERNAL_API_KEY: !Ref InternalApiKey
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !Ref InstagramSqsQueueArn
            BatchSize: 1
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints: ['src/instagram.ts']
        Format: cjs
        Minify: true

Outputs:
  FacebookFunctionName:
    Description: 'The name of the Facebook Campaign Orchestrator Lambda function'
    Value: !Ref FacebookCampaignFunction
  InstagramFunctionName:
    Description: 'The name of the Instagram Campaign Orchestrator Lambda function'
    Value: !Ref InstagramCampaignFunction
